// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd1qocZKygP1zxS1Mq11B8-eDHFEqUMl4',
    appId: '1:349182294836:web:8ecaa835b9ab3060a2c361',
    messagingSenderId: '349182294836',
    projectId: 'elearning-5bd35',
    authDomain: 'elearning-5bd35.firebaseapp.com',
    storageBucket: 'elearning-5bd35.appspot.com',
    measurementId: 'G-PWCH79KM2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATcO5y0zwXHFun0nrH7f7Y3WVd6uqzs_s',
    appId: '1:349182294836:android:a2c30a2f859ee651a2c361',
    messagingSenderId: '349182294836',
    projectId: 'elearning-5bd35',
    storageBucket: 'elearning-5bd35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrr4Oueff5cRUaI93WI3KvyZrXdbyYhAs',
    appId: '1:349182294836:ios:977b4471b09cd840a2c361',
    messagingSenderId: '349182294836',
    projectId: 'elearning-5bd35',
    storageBucket: 'elearning-5bd35.appspot.com',
    iosClientId: '349182294836-ims0s05engr3lvqcotpsgqg7vvjhu5vv.apps.googleusercontent.com',
    iosBundleId: 'com.example.apps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrr4Oueff5cRUaI93WI3KvyZrXdbyYhAs',
    appId: '1:349182294836:ios:216def82f1c5385ea2c361',
    messagingSenderId: '349182294836',
    projectId: 'elearning-5bd35',
    storageBucket: 'elearning-5bd35.appspot.com',
    iosClientId: '349182294836-773ntl56oi32gv5ri16dhhp7ag1mij76.apps.googleusercontent.com',
    iosBundleId: 'com.example.apps.RunnerTests',
  );
}
